DATASET:
  # root_dataset: "../img_apartmentM/" # train dataset
  root_dataset: "../hw1_data/floor2/" # val dataset
  list_train: "../img_apartment0/metal_training.odgt"
  list_val: "../hw1_data/floor2/hw1_floor2.odgt" # "../img_apartment0/metal_validation.odgt"
  num_class: 101
  imgSizes: (300, 375, 450, 525, 600)
  imgMaxSize: 1200 # origin is 1000
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True

MODEL:
  arch_encoder: "resnet101"
  arch_decoder: "upernet"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 60 # origin is 40
  start_epoch: 50 # origin is 0
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: True # origin is False
  checkpoint: "epoch_60.pth"

TEST:
  checkpoint: "epoch_60.pth"
  result: "./"

DIR: "ckpt/apartment0-resnet101-upernet"
